### ISSUE TITLE
eliminate model.validate overrides

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#13]
model`.validate()` is marked as deprecated: http://docs.sencha.com/extjs/5.1/5.1.1-apidocs/#!/api/Ext.data.Model-method-validate

The new method, model`.getValidation()` returns an `Ext.data.Validation` instance instead of `Ext.data.ErrorCollection` (which is also marked deprecated)

We need to convert or eliminate any instances where our models override `validate`, and find any places where `.validate()` is being called and convert it to use `.getValidation()` instead and test that it is behaving correctly.

The new `Ext.data.Validation` class is marked as private, unlike the deprecated `Ext.data.ErrorCollection` which was public and had examples of how to add your own errors to it. Maybe there is a better way now to add our custom validation logic via the new `validators` config so that `getValidation` doesn't need to be overridden and the private `Ext.data.Validation` class doesn't need to be manipulated directly.

**Comment by BillClinton** [comment]
The only instance of a model overriding validate is in model/person/ContactPoint and is corrected here: https://github.com/SlateFoundation/slate-admin/commit/5ec075b1b730c18c0bc84f87208b6a02c5f4c2e9

**Comment by themightychris** [comment]
@BillClinton the getValidation method doesn't seem to be the correct place to insert our custom validation logic as the new getValidation method isn't supposed to be what refreshes the validation state, its job is just to get the current validation state so using it as a hook for our own logic is disharmonious with the frameworks pipeline.

after some preliminary searching though I can't find any blessed way to do it. The [validator base class doc](http://docs.sencha.com/extjs/5.1/5.1.1-apidocs/#!/api/Ext.data.validator.Validator-method-validate) says you can override its validate method for custom validators, and then it documents that its validate method gets passed the whole record as its second param, but looking in the code that calls it that doesn't seem to be the case.

seems like a forum post is in order...can you try throwing a breakpoint in a custom validator's validate method and verify that the place the framework calls it from doesn't pass the record?

**Comment by themightychris** [comment]
@BillClinton found a bug report, looks like this issues has stuck around through all 5.x release ugh https://www.sencha.com/forum/showthread.php?294061

**Comment by themightychris** [comment]
@BillClinton someone shared an override package in that thread but if that's the route we have to go I don't want to use it as-is as it overrides methods that contain a lot of code copied from the framework without any strict controls in place to ensure its only applied against the specific version of the framework it was copied from.

What we might need to do is implement the overrides in a 5.1.??? branch of our sencha-hotfixes package (that package has a sep branch for every ExtJS release and each override has an after-define callback that tests the runtime framework version and issues mismatch warnings). That way we can ensure the override implementations are based on the same versions that came with each framework version

**Comment by BillClinton** [comment]
@themightychris Since we are talking about validating one field here, maybe just remove the validation and take care of it server side and/or in the controller?  validate() was never specifically called on this model.  The ContactPoint controller calls IsValid() twice before a conditional record save, but does not have an else on those conditionals where errors are dealt with or displayed to the user.

**Comment by themightychris** [comment]
@BillClinton instant validation based on type is essential here, this is a very high-volume and highly error-prone workflow

**Comment by BillClinton** [comment]
This issue can be analyzed for closure.  relevant files are: app/validator/CallbackValidator.js and app/model/person/ContactPoint.js along with the ext-5.1.1.451 branch of jarvus-hotfixes

**Comment by BillClinton** [comment]
@themightychris The CallbackValidator implementation contained in the files in the above comment exists in the development branch.  Can we mark this closed?
