### ISSUE TITLE
push all sencha packages to standalone repos

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#15]
For each package currently committed under `sencha-workspace/packages`, we need to:

1. Asses the package for framework interop. If the package is or could be compatible with both Touch and Ext JS, name (or leave it named) `jarvus-featurename`. If it is fundamentally touch- or ext- specific, or needs to be for now until more time could be put into a universal version, name it `jarvus-ext-featurename` or `jarvus-touch-featurename`
2.  create a public repo under the JarvusInnovations org with the repo name matching the package name
3. Add an entry to chaki.io for the package
4. Add/update the package to SlateAdmin's `requires` array in app.json
5. Delete and remove from git the package's old tree under `sencha-workspace/packages/`
6. Check out the new package repo into `sencha-workspace/packages/`
7. Add a `/packages/jarvus-ext-featurename` line to `sencha-workspace/.gitignore`

The [chaki CLI](https://github.com/JarvusInnovations/chaki) should eventually do 6-7 automatically for all required packages when you first build an app or checkout a project -- currently it can handle loading the app's config, looking up all the required packages on chaki.io and checking out their repos in the packages directory -- but it's pretty dumb and would probably choke right now on our current mix of legacy and manageable packages)

**Comment by BillClinton** [comment]
current package inventory:

jarvus-apikit  - Chaki.io package exists
emergence-apikit - Chaki.io package exists
jarvus-hotfixes - exists in Chaki.io w/ext-5.1.1.451 branch (github name -> sencha-hotfixes)
jarvus-ext-actionevents - Chaki.io package exists
jarvus-ext-lazydata - Chaki.io package Jarvus-lazydata exists w/ext-5.1.1.451 branch
jarvus-ext-glyphs - Chaki.io package exists
jarvus-ext-routing - Chaki.io package exists
jarvus-ext-treerecords - Chaki.io package exists
jarvus-ext-searchfield - Chaki.io package exists

slate-admin-theme - deprecated

**Comment by BillClinton** [comment]
@themightychris the only package I do not see in the development branch version of app.json is jarvus-apikit.  Shall we add that, or are we counting on the jarvus-apikit requirement in emergence-apikit?

Once we resolve the above question, can we consider this issue closed?

**Comment by BillClinton** [comment]
@themightychris this PR should close this issue.
https://github.com/SlateFoundation/slate-admin/pull/43
