### ISSUE TITLE
JSON export response error when request contains &include=*

### ISSUE THREAD

**Issue by BillClinton** [SlateFoundation/slate-admin#19]
When exporting to JSON format, the SlateAdmin.controller.People.onExportFormatButtonClick adds the "&include=*" parameter to the request:

495         if (exportFormat == 'json') {
496             params.include = '*';
497         } 

This results in a server error: Fatal error: Class 'Slate\Assets\Ticket' not found in /emergence/sites/v1-demo/data/2013 on line 6.   eg: http://v1-demo.node0.slate.is/people?format=json&q=group%3Aclass_of_2013&include=*

The request succeeds without includes, eg, http://v1-demo.node0.slate.is/people?format=json&q=group%3Aclass_of_2013

**Comment by themightychris** [comment]
This was the result of a bad partial merge that existing on v1.slate.is for awhile. v1.slate.is and v2.slate.is are free of this issues now, although v1-demo is still affected because it is out of date
