### ISSUE TITLE
audit commented-out overrides/patches

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#2]
Review all the patches/overrides commented out in 3889cc31ae18dd0e98775c006cc62b3485701fec
- Determine what it did and if the current app is functioning as intended without it
- if it was a framework bug fix, file it in an ext-4.2.2.1144 branch in https://github.com/JarvusInnovations/sencha-hotfixes
- either remove the commented out line, or upgrade the bug fix and put it in an ext-5.1.1.451 branch of sencha-hotfixes

**Comment by BillClinton** [comment]
Note: Jarvus.ext.override.data.RequireLoadedStores was uncommented in commit:  https://github.com/SlateFoundation/slate-admin/commit/fc396525ccede77912f2aea9a04ada5d36c81e2f

**Comment by BillClinton** [comment]
@themightychris I removed RequireLoadedStores requirement. This was the only override still refrenced in the development branch Application.js This override is included in the ext-5.1.1.451 branch of the jarvus-lazydata package and should not need to be referenced here (right?).  Change in branch audit/overrides-patches-2.
