### ISSUE TITLE
All People button changes size

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#25]
Before selected, the button is cut off and looks like this 
![screen shot 2015-06-18 at 2 32 08 pm](https://cloud.githubusercontent.com/assets/5123794/8238967/e82030e0-15c6-11e5-9dc8-3fb038a0088b.png)

After selection, it spaces correctly 
![screen shot 2015-06-18 at 2 32 17 pm](https://cloud.githubusercontent.com/assets/5123794/8238972/f2ff3326-15c6-11e5-8336-1ccf88e816e1.png)

**Comment by themightychris** [comment]
@ryon it looks like that advanced search fieldset is pulling some undesirable styles from our frontend css?

**Comment by themightychris** [comment]
@ryon can also confirm there is weird padding or something pushing All People off center until it's selected for the first time
