### ISSUE TITLE
Add New Relationship prompt cut off

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#26]
The prompt to add a new relationship can not be read because it is cut off
![screen shot 2015-06-18 at 2 34 34 pm](https://cloud.githubusercontent.com/assets/5123794/8239032/5b932992-15c7-11e5-90bc-e1b8e9c1bc3d.png)

**Comment by themightychris** [comment]
@ckunkel please retest this from a fresh incognito browser window. I can't reproduce this. You can resize the columns there and your browser will remember them between refreshes so you may have just made the column narrower at some point.
