### ISSUE TITLE
groups don't get created with correct classes

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#29]
Groups created through the groups settings screen don't get created with the correct class names.

Top level groups should have the Organization class while the rest are Groups

Ensure the Group model is getting the correct class set before being saved to the server, it should be `Emergence\People\Groups\Organization` for the top-level groups and `Emergence\People\Groups\Group` for all child groups.

**Comment by BillClinton** [comment]
to avoid merge conflicts and for ease of testing, I fixed this in the features/groupactioncolumns-32 branch rather than creating a new branch.  Ready for Q&A
