### ISSUE TITLE
convert settings->groups to use action column instead of context menu

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#32]
The Settings > Groups screen uses a right-click menu for some key actions. The context menu should be removed and all its actions instead implemented in an ActionColumn. Use the jarvus-actionevents package (already included in slate-admin) to receive the clicks from the same controller already handling the context menu.

The People>Details>Contacts and Courses>Details>Roster grids already make use of actioncolumns/actionevents and can be used as a reference.

Assign this tank to ryon after it is implemented for final icon selection and UI polishing

**Comment by BillClinton** [comment]
@ryon the action columns are now implemented in the issue-32-groups-action-columns branch

check out app/view/groups/Manager.js lines 50-70

**Comment by BillClinton** [comment]
need to change actioncolumn implementation

**Comment by themightychris** [comment]
@BillClinton what does that mean? There's a problem with the jarvus-actionevents override?

**Comment by BillClinton** [comment]
@chris no, I wasn't using it properly.  Also package wasn't being included in app.json

**Comment by BillClinton** [comment]
@ryon should be ready for actioncolumn icons now.  
branch: issue-32-groups-action-columns branch
check out app/view/groups/Manager.js lines 51-66

**Comment by themightychris** [comment]
@BillClinton passing this one back to you until the feature branch is rebased on top of development, reassign to ryon when it's ready

**Comment by BillClinton** [comment]
@ryon branch name is now features/groupactioncolumns-32

app/view/groups/Manager.js lines 51-66
url : #settings/groups

**Comment by BillClinton** [comment]
@ryon settings files have been merged into development branch.  

 Settings->Groups grid needs icons for action columns and button for create in bottom toolbar: app/view/groups/Manager.js

**Comment by ryon** [comment]
@themightychris Icons are in. See https://github.com/SlateFoundation/slate-admin/issues/63#issuecomment-139076487

**Comment by themightychris** [comment]
Closed in #68
