### ISSUE TITLE
create Settings->Terms screen

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#33]
The Settings->Term screen should provide the same functionality for term models as the groups screen does for groups. Both are hierarchies with some editable columns.

The Groups screen has a pending issue #32 to convert its context menu to action column buttons, so be sure to use action column buttons for this new screen too

**Comment by BillClinton** [comment]
@themightychris please see if the above pull request can be merged into development

**Comment by BillClinton** [comment]
@ryon these files are now in the development branch.  

 Settings->Terms grid needs icons for action columns and button for create in bottom toolbar: app/view/settings/terms/Manager.js
