### ISSUE TITLE
create Settings->Departments screen

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#34]
The Settings->Departments screen should be a simple grid for editing/creating departments. Departments are a simple flat table

**Comment by BillClinton** [comment]
@themightychris please see if the above pull request can be merged into development

**Comment by BillClinton** [comment]
@ryon these files are now in the development branch.  

 Settings->Departments grid needs icons for action columns and button for create in bottom toolbar: app/view/settings/departments/Manager.js
