### ISSUE TITLE
create Settings->Courses screen

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#35]
The Settings->Courses screen should be a simple grid for editing/creating courses. Courses are a simple flat table (and not to be confused with sections).

**Comment by BillClinton** [comment]
@themightychris please see if the above pull request can be merged into development

**Comment by BillClinton** [comment]
@ryon these files are now in the development branch.  

 Settings->Courses grid needs icons for action columns and button for create in bottom toolbar: app/view/settings/courses/Manager.js
