### ISSUE TITLE
Adding relationships errors

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#44]
Multiple issues exist 
1. After selecting a person and then clicking off their name, no name is displayed (though it does reappear if the dropdown is reselected). 
2. Record does not save

**Comment by ckunkel** [comment]
This remains an issue.

**Comment by themightychris** [comment]
In my recent test I didn't have any problem adding a relationship, but rather there is a crash when trying to parse an existing relationship on load
