### ISSUE TITLE
Can't add contact points

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#45]
Fields are enterable but once selecting another user and navigating back, the information was not saved.

**Comment by BillClinton** [comment]
@themightychris I believe this may be an Emergence issue.  I am seeing the following response for contact-points on v1-demo.node0.slate.is:

Fatal error: Cannot instantiate abstract class Emergence\People\ContactPoint\AbstractPoint in /emergence/sites/v1-demo/data/2024 on line 1321

**Comment by ckunkel** [comment]
Contact points can now be added but this produces a secondary issue.  See issue #48  https://github.com/SlateFoundation/slate-admin/issues/48
