### ISSUE TITLE
Selecting a contact point label doesn't jump to data field

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#54]
In the ext-4 version of slate-admin, selecting a preset label would jump you immediately over to editing the data field: http://v1.slate.is/manage

This isn't working in the new slate-admin

Find the code that was handling that before and repair it

**Comment by aharley40** [comment]
@themightychris Just pushed this code.

**Comment by themightychris** [comment]
@aharley40 please reference the issue number in your commit message or reference the commit hash in your comment in the issue

**Comment by aharley40** [comment]
@themightychris Finished, please close https://github.com/SlateFoundation/slate-admin/commit/eb18ad255390ee155822bd2fcf8676663ecebfc1

**Comment by themightychris** [comment]
@aharley40 your changes ignore the warning in the comment, create new problems, and don't fix the original issue. Reverting for now

**Comment by themightychris** [comment]
Reverted eb18ad2 with 8ada285a3cc24c9945e9086920a8e3c0474d399e

**Comment by aharley40** [comment]
@themightychris I couldn't reproduce the error once I made the change. I tried putting an events on all the editors startEdit events and still didn't catch the rogue event you mentioned. Could I get some more steps to reproduce?

**Comment by aharley40** [comment]
@themightychris I got access to the editor to force completion on select. This combined with the other events in place jumps the combo onto the next field. 

https://github.com/SlateFoundation/slate-admin/commit/9c5e74db9a2ca29bb1a2d7f9f5d3c191d158d9c7

**Comment by aharley40** [comment]
@themightychris Do you approve of the new workflow?
