### ISSUE TITLE
Address style issues

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#55]
See comments here: https://github.com/SlateFoundation/slate-admin/commit/d2cbc3b82c5b00633d88797ac53315b4c2da1121

Ensure that all the files you've committed recently follow the project's style guidelines consistently:
- No trailing whitespace
- Sencha style guidelines
- No tabs
- Do not build your own URLs, use `SlateAdmin.API.buildUrl(path)`

Do not mix style changes with code changes in the same commits as you address these issues

**Comment by aharley40** [comment]
@themightychris Addressed changes, please close.

**Comment by themightychris** [comment]
@aharley40 manual URL building is still being done in two places, please fix and TEST:
- https://github.com/SlateFoundation/slate-admin/blob/development/sencha-workspace/SlateAdmin/app/view/people/details/progress/Previewer.js#L96
- https://github.com/SlateFoundation/slate-admin/blob/development/sencha-workspace/SlateAdmin/app/view/progress/interims/Printer.js#L225

**Comment by aharley40** [comment]
@themightychris Fixed the custom url's 

https://github.com/SlateFoundation/slate-admin/commit/c192be7859e344e2f920dba54f086bf2689efb16
