### ISSUE TITLE
Use view-instantiated grouptree stores and eliminate duplicate controller stores

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#57]
Undo 345b7c1d93fd32bdef2c2c9e0b718c67846ff4c2 and remove the `stores` references to GroupTree in the Groups and People controllers. Instead require the store prototype from each of the two views that need it and configure store with `{ xclass: 'SlateAdmin.stores.people.GroupTree' }`

**Comment by aharley40** [comment]
@themightychris We worked on this for a bit yesterday. It stills needs cleaning up for record creating and deleting.  I'll work on it's implementation after I take care of other git styling issues. Can we close this ticket and make something more relevant for the other tasks.

**Comment by themightychris** [comment]
@aharley40 closing
