### ISSUE TITLE
clean code formatting in old progress code

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#58]
Leading commas and { on a separate line from control statements are still prevalent in the progress code. All old code must be made to conform to Sencha's code guidelines before committing to slate-admin

**Comment by aharley40** [comment]
@themightychris While cleaning it up i noticed that our patch to Emergence.proxy.Records fixed up the saving events. I'm going to circle back to finishing this after I tackle the contact points issue and clean up the cbl export scripts.

**Comment by aharley40** [comment]
@themightychris I finished implementing the guidelines https://github.com/SlateFoundation/slate-admin/commit/8ed97e166909850ae15cfbeddeceb65157eb73fb

**Comment by themightychris** [comment]
@aharley40 lots of rouge leading commas remain, use Visual Studio Codes' multi-file regex searching ability to find all the remaining instances:

![image](https://cloud.githubusercontent.com/assets/458494/9750457/1e44c0a2-5666-11e5-8bdc-fb63004ae1be.png)

**Comment by aharley40** [comment]
@ckunkel This is the only task I had time to work on yesterday. Once I finish this I'm going to to do https://github.com/SlateFoundation/slate-admin/issues/54 and https://github.com/SlateFoundation/slate-cbl/issues/49

**Comment by aharley40** [comment]
@themightychris Finished removing wildling commas https://github.com/SlateFoundation/slate-admin/commit/3aed71adaeeb0cb8497895a6ad61eb1c95a965ac

**Comment by themightychris** [comment]
Closed in #68
