### ISSUE TITLE
Review progress styling and implement best practices

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#60]
The Sass for progress notes got hack-jobbed into v2 slate-admin

Inspect the Progress.scss files under src and var of the SlateAdmin app sass, it seems like it needs some modernizing of what variables its using with the new slate-admin

Harley originally copied all these variables into the theme's Component.scss: SlateFoundation/slate-theme@829fe14a5946cd48608d18613f8e08cc9dbcb241

But i noticed that was duplicating a bunch of stuff thats in glyph-colors now and removed those changes: SlateFoundation/slate-theme@a9a8e61b84a02723aef2a6ae0d1339c853058353

But src/../Progress.scss wouldn't compile because dark-ui-color wasn't defined (even though it was defined at the theme level) so i had to add that and muted-color defaults to var/../Progress.scss to get the app to compile: 5694488153cdd6f13648b3e77ae86f8904557140

**Comment by ryon** [comment]
I looked over this, and moving those variables back to the theme seems to make sense to me, and works. See https://github.com/SlateFoundation/slate-theme/commit/be2ef928e8319a0999f504847e5bd3b747365f1d and b3ff9eac7f2836b259079db99ae668519ebd4d55 @themightychris

**Comment by themightychris** [comment]
Closed in #68
