### ISSUE TITLE
New settings grids need glyphs

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#63]
They just have placeholders now:
![image](https://cloud.githubusercontent.com/assets/458494/9724633/dc20d390-55a8-11e5-9fc8-5bfc0db99001.png)

**Comment by themightychris** [comment]
This issue is a dupe of #32

**Comment by themightychris** [comment]
Actually it's more a superset of #32, all the settings grids need glyphs now

**Comment by ryon** [comment]
@themightychris Glyphs have been added to settings grids in 5b0c3beae85ea862760400ca1b2f8fe3266304e7.

<img width="197" alt="screen shot 2015-09-09 at 7 56 53 pm" src="https://cloud.githubusercontent.com/assets/1154929/9777047/3a07d122-572d-11e5-8174-1c1b587bbdec.png">

**Comment by themightychris** [comment]
Closed in #68
