### ISSUE TITLE
Models missing requires for validators

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#64]
Saving contact points is currently broken in builds because the presence validator isn't being included in builds. Go through every model is SlateAdmin and ensure that each model class requires every validator type that it uses.

**Comment by aharley40** [comment]
@themightychris Finished, https://github.com/SlateFoundation/slate-admin/commit/95351d40ba3092facdb29ecfde4d71c7f3fecd50

**Comment by ckunkel** [comment]
@chris the functionality seems to be working here but you'll need to confirm each model is accounted for by code review.

**Comment by aharley40** [comment]
@themightychris Finished adding validator requires, https://github.com/SlateFoundation/slate-admin/commit/aee19923a1d5cc04bd16b892fdaeb2e87c9dffec

**Comment by themightychris** [comment]
Closed in #68
