### ISSUE TITLE
Links from settings grid into courses browser don't work

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#70]
When you click any of the actioncolumn browse buttons from the settings terms/deps/courses grids you get immediately redirected to the all-courses route. Look at how the people section uses suspendState / pushState / syncState workflows to prevent that

This might be related do these outstanding wrike issues:
- https://www.wrike.com/open.htm?id=29031615
- https://www.wrike.com/open.htm?id=25486873

**Comment by aharley40** [comment]
@themightychris Looks like all the main views have this issue when trying to load a subroute before the nav panel expand. OnNavPanel expand changes the route and causes the reloading. Please look over this implementation and I'll transfer it to the other sections if approved. 

https://github.com/SlateFoundation/slate-admin/commit/24a41d56553abfdf08349e293efb7f04b453e068

**Comment by themightychris** [comment]
@aharley40 our suspendState method is supposed to be accomplishing this, it works in the people section which has been much more tightly refined

**Comment by themightychris** [comment]
@aharley40 I pretty much never want to use suspendEvents, it's a cludge of a way to fix things in most cases

**Comment by themightychris** [comment]
@aharley40 see these notes and please revise https://github.com/SlateFoundation/slate-admin/commit/24a41d56553abfdf08349e293efb7f04b453e068#commitcomment-13219723

**Comment by aharley40** [comment]
@themightychris Implemented suggestions from notes. 

https://github.com/SlateFoundation/slate-admin/commit/9770f5cf2879fee7bb5606066c7736a3f9d1d915
