### ISSUE TITLE
Detab all imported progress code

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#71]
All the classes imported from progress are full of tabs. Convert them all to spaces and commit the changes in a commit that is ONLY whitespace changes and no other changes.

**Comment by aharley40** [comment]
@themightychris Converted remaining tabs to spaces. 

https://github.com/SlateFoundation/slate-admin/commit/6ef29320f315af7f210e6e2ab61fa71f3aafa404

**Comment by aharley40** [comment]
@themightychris Please inspect this.
