### ISSUE TITLE
Add getCurrentYear method to terms store

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#72]
Update the /terms request handler and the Terms store to also expose the current year alongside the current term. The current year can be obtained by calling `->getMaster()` on the current term

In some places where we set a default selection on a term combo it makes more sense to use the entire current year rather than the current quarter

**Comment by aharley40** [comment]
@themightychris Which sections should should have this? Currently, everything has been changed to getCurrentTerm or getReportingTerm from your suggestions.
