### ISSUE TITLE
Server-side errors when saving contact point aren't rendered to UI

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#73]
When saving a contact point results in a server-side error, a javascript error is produced where the error should instead be presented to the user.

One way to invoke a server-side error is to try and save an email point that matches the address in an existing email point

The functionality for relaying a validation error to the user via the grid relied on an override feature that was implemented here: https://github.com/JarvusInnovations/ext-library/blob/master/Jarvus/ext/override/view/TableErrors.js

This override needs to be implemented in a new package, `jarvus-griderrors`, and tested against extjs 5

**Comment by aharley40** [comment]
@themightychris Please review and close 
https://github.com/SlateFoundation/slate-admin/commit/eeb22dc56d788324b3ea02d796298c70d115bdc2
