### ISSUE TITLE
Fix namesPath for groups

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-admin#74]
The current namesPath solution does not work:
- the convert function runs during model instantiation and models are instantiated before being added to their parent, therefore getPath always returns only the current part of the hierarchy when called from a convert function
- getPath includes the root node which is meaningless when called on a node that IS in a tree
- namesPath is needed in the flag Groups store where there is no tree structure

The place where namesPath is important is in the groups tagsfield under the profile editor, which is driven by the non-tree groups store:

![screenshot from 2015-09-10 14 33 16](https://cloud.githubusercontent.com/assets/458494/9797421/073f8982-57c9-11e5-9107-6456e2851da2.png)

The non-tree Groups store should populate namesPath in a `load` event listener and the convert method should be removed. getPath won't be usable

**Comment by aharley40** [comment]
@themightychris Implemented the changes you suggested. https://github.com/SlateFoundation/slate-admin/commit/fb4808b3c20643229850c1406d1800f06696e3a4

**Comment by themightychris** [comment]
@aharley40 closing following my revisions: af9474c4ed33c44be4f410fdb698bab70337a308
