### ISSUE TITLE
Can not expand folders in /manage#settings

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#83]
Terms and Groups folders can not be expanded by clicking. They only expand once you add a new sub item. 

What should happen: expansion of any folder by clicking on it.

**Comment by themightychris** [comment]
@ckunkel they're only supposed to expand when you click on the "expander" icon (A [+] or an > arrow). Do you see the expander icon and does it work?

We've wired some of the trees in the app to automatically expand on select, but on the newer ones the decision has yet to be made what the best workflow is. Expanding on select can make things jarring when inline editing is involved too

**Comment by ckunkel** [comment]
That makes sense. I also realize that I found it on an older version and didn't test on the most current V2. We're good here.
