### ISSUE TITLE
Progress Notes - Fonts

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#90]
The progress note composer has an ugly serif font. The `fontFamilies` config can control what fonts are available and the undocumented `defaultFont` config can control which is used by default. Have Ryon pick a default font and list of fonts to configure it with. If Ryon wants to force only one font to be used, it looks like you can set `enableFont: false` to disable picking fonts and set `defaultFont` to what we want them to use (edited)

**Comment by aharley40** [comment]
@ckunkel Looks like this was already implemented on my end. Not sure if the class is already there. @ryon What class should I add if there isn't already one there?

https://github.com/SlateFoundation/slate-admin/blob/development/sencha-workspace/SlateAdmin/app/view/people/details/progress/note/Form.js#L19-L20
