### ISSUE TITLE
Worksheets: Disable sheet doesn't delete it the first time

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#92]
When disabling a worksheet, it simply puts it in alphabetical order (if it was recently created and not already organized that way), rather than disabling it. If you immediately disable it a second time, it does disable it and remove it from the list.

**Comment by aharley40** [comment]
@ckunkel I addressed this in my latest commit and forgot to tag it. It behaves as expected now

**Comment by ckunkel** [comment]
@aharley40 I'm still seeing the same error.
