### ISSUE TITLE
TPS Narratives Implemented

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#95]
Implement Narratives on Philadelphia School site with the following changes
1. Remove grade selector
2. Add a text entry field titled “Absences” that requires a number entry
3. Move “Assessment” text entry section above standards and rename to “Curriculum Overview”

**Comment by ckunkel** [comment]
Updates to language and layout:
- [] Add narrative reports button on dashboards
- [] My classes only button hangs
- [] Curriculum Overview moved centrally for all students in a section
- [] Dropdown grading language as a setting
Identified area of concern
Progressing with support
Working towards independence
Working independently
- [] Title “Standards-based grading worksheet” replaced with “Checklist” (setting)
- [] “Double-click to enable SBG” should be “Double-click to add Checklist” (les important)
- [] “Notes from Teacher” should be “Comments”

**Comment by themightychris** [comment]
@ckunkel I recommend against changing the dropdown grading text. These values correspond to the 1-4 scale we have there already. SLA has full phrases that correspond to to the 1-4 scale too but they only get printed on the report cards.

Putting the full phrases in the dropdown would:
1. make the dropdown need to be a lot wider and take up room we desperately need fro the standards sentences
2. make it harder for teachers to rapidly key in values
3. not really be necessary for teachers since they know what the scale is

**Comment by ckunkel** [comment]
@themightychris It definitely is more clear for teachers to not have to translate the numbers to their four levels and rather see exactly what they're entering. Keying it in would be affected but that is minor and the real issue is the spacing. I do think a drop down that opens wider below the standard could work while not affecting the space for the standard to lay out. Thoughts?

**Comment by ckunkel** [comment]
- [ ] Worksheet name after selected reverts to "Deleted Worksheet"
- [ ] After editing Title or Description of a worksheet and saving, the save hangs on "Saving worksheet..." but the changes persist after a refresh. (saving after editing prompts is fine).

**Comment by themightychris** [comment]
@ckunkel fixed and deployed

**Comment by ckunkel** [comment]
@themightychris I'm still seeing the [Deleted Worksheet] issue

![screen shot 2015-11-20 at 6 01 26 pm](https://cloud.githubusercontent.com/assets/5123794/11314133/bf58b088-8fb0-11e5-82f7-c39854bcaa43.png)

**Comment by themightychris** [comment]
@ckunkel fixed that issue and deployed to TPS staging
